#ifndef PARAMS_H
#define PARAMS_H

#include "config.h"

#define DILITHIUM_SEEDBYTES 32
#define DILITHIUM_CRHBYTES 64
#define DILITHIUM_TRBYTES 64
#define DILITHIUM_RNDBYTES 32
#define DILITHIUM_N 256
#define DILITHIUM_Q 8380417
#define DILITHIUM_Q_BITLEN 23
#define DILITHIUM_D 13
#define ROOT_OF_UNITY 1753

#if DILITHIUM_MODE == 2
#define DILITHIUM_K 4
#define DILITHIUM_L 4
#define DILITHIUM_ETA 2
#define DILITHIUM_TAU 39
#define DILITHIUM_BETA 78
#define DILITHIUM_GAMMA1 (1 << 17)
#define DILITHIUM_GAMMA2 ((DILITHIUM_Q-1)/88)
#define DILITHIUM_OMEGA 80
#define DILITHIUM_CTILDEBYTES 32

#elif DILITHIUM_MODE == 3
#define DILITHIUM_K 6
#define DILITHIUM_L 5
#define DILITHIUM_ETA 4
#define DILITHIUM_TAU 49
#define DILITHIUM_BETA 196
#define DILITHIUM_GAMMA1 (1 << 19)
#define DILITHIUM_GAMMA2 ((DILITHIUM_Q-1)/32)
#define DILITHIUM_OMEGA 55
#define DILITHIUM_CTILDEBYTES 48

#elif DILITHIUM_MODE == 5
#define DILITHIUM_K 8
#define DILITHIUM_L 7
#define DILITHIUM_ETA 2
#define DILITHIUM_TAU 60
#define DILITHIUM_BETA 120
#define DILITHIUM_GAMMA1 (1 << 19)
#define DILITHIUM_GAMMA2 ((DILITHIUM_Q-1)/32)
#define DILITHIUM_OMEGA 75
#define DILITHIUM_CTILDEBYTES 64
#endif

#define DILITHIUM_POLYT1_PACKEDBYTES  320
#define DILITHIUM_POLYT0_PACKEDBYTES  416
#define DILITHIUM_POLYVECH_PACKEDBYTES (DILITHIUM_OMEGA + DILITHIUM_K)

#if DILITHIUM_GAMMA1 == (1 << 17)
#define DILITHIUM_POLYZ_PACKEDBYTES   576
#elif DILITHIUM_GAMMA1 == (1 << 19)
#define DILITHIUM_POLYZ_PACKEDBYTES   640
#endif

#if DILITHIUM_GAMMA2 == (DILITHIUM_Q-1)/88
#define DILITHIUM_POLYW1_PACKEDBYTES  192
#elif DILITHIUM_GAMMA2 == (DILITHIUM_Q-1)/32
#define DILITHIUM_POLYW1_PACKEDBYTES  128
#endif

#if DILITHIUM_ETA == 2
#define DILITHIUM_POLYETA_PACKEDBYTES  96
#elif DILITHIUM_ETA == 4
#define DILITHIUM_POLYETA_PACKEDBYTES 128
#endif

#define DILITHIUM_CRYPTO_PUBLICKEYBYTES (DILITHIUM_SEEDBYTES + DILITHIUM_K*DILITHIUM_POLYT1_PACKEDBYTES)
#define DILITHIUM_CRYPTO_SECRETKEYBYTES (2*DILITHIUM_SEEDBYTES \
                               + DILITHIUM_TRBYTES \
                               + DILITHIUM_L*DILITHIUM_POLYETA_PACKEDBYTES \
                               + DILITHIUM_K*DILITHIUM_POLYETA_PACKEDBYTES \
                               + DILITHIUM_K*DILITHIUM_POLYT0_PACKEDBYTES)
#define DILITHIUM_CRYPTO_BYTES (DILITHIUM_CTILDEBYTES + DILITHIUM_L* DILITHIUM_POLYZ_PACKEDBYTES + DILITHIUM_POLYVECH_PACKEDBYTES)

#endif
